Quanticade/Quanticade

Source/uci.c
LTC
Elo   | 16.85 +- 5.87 (95%)
Games | N: 4148 W: 1204 L: 1003 D: 1941
Penta | [34, 392, 1037, 561, 50]
STC
Elo   | 25.63 +- 7.76 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 3.00]
Games | N: 3218 W: 1094 L: 857 D: 1267
Penta | [52, 303, 713, 438, 103]
=> uci.c: Change to 1/20 of time as default

Source/search.c
Elo   | 4.28 +- 3.28 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15598 W: 4157 L: 3965 D: 7476
Penta | [221, 1803, 3600, 1913, 262]
=> Quiescence tt

Source/search.c
bench: 4048485
Elo   | 0.42 +- 2.72 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 22246 W: 5771 L: 5744 D: 10731
Penta | [322, 2651, 5159, 2660, 331]
=> search.c: store best_score instead of alpha on fail low

Source/search.c
Elo   | 12.72 +- 6.32 (95%)
Games | N: 3442 W: 853 L: 727 D: 1862
Penta | [20, 365, 830, 481, 25]
Elo   | 11.72 +- 6.27 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4388 W: 1208 L: 1060 D: 2120
Penta | [65, 463, 1010, 571, 85]
Gains aprox 12 elo on STC and LTC.
The formula is VERY much not final.
=> Late Move Pruning

Source/search.c
Elo   | 37.06 +- 11.61 (95%)
Games | N: 1214 W: 386 L: 257 D: 571
Penta | [8, 101, 284, 182, 32]
bench: 3281216
=> search.c: NMP to higher depth

Source/search.c
Elo   | 19.32 +- 7.95 (95%)
LLR   | 3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2322 W: 661 L: 532 D: 1129
Penta | [18, 218, 577, 313, 35]
bench: 3039195
=> search.c: Dynamic NMP

Source/search.c
Elo   | 12.80 +- 6.55 (95%)
Games | N: 3666 W: 1006 L: 871 D: 1789
Penta | [34, 397, 860, 484, 58]
Elo   | 5.03 +- 3.79 (95%)
LLR   | 2.90 (-2.25, 2.89) [0.00, 5.00]
Games | N: 12652 W: 3399 L: 3216 D: 6037
Penta | [201, 1510, 2799, 1537, 279]
bench: 2659605
=> search.c: RFP to higher depths

Source/pvtable.c
Elo   | 18.71 +- 8.12 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2528 W: 701 L: 565 D: 1262
Penta | [27, 254, 594, 334, 55]
https://chess.aronpetkovski.com/test/2226/
Elo   | 22.42 +- 8.44 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1924 W: 486 L: 362 D: 1076
Penta | [14, 170, 471, 292, 15]
https://chess.aronpetkovski.com/test/2227/
bench: 2242645
=> pvtable.c: Fix replacment condition in TT

Source/search.c
Elo   | 0.71 +- 1.94 (95%)
LLR   | 3.06 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 41780 W: 10431 L: 10346 D: 21003
Penta | [470, 5102, 9734, 5041, 543]
https://chess.aronpetkovski.com/test/2272/
passes non reg.
fails to pass gainer bounds. Which is expected given its probably a tiny tiny gainer.
the change is mostly for the future
=> More agressive lmp

Source/search.c
bench: 5131429
Elo   | 20.09 +- 8.22 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2182 W: 555 L: 429 D: 1198
Penta | [14, 218, 515, 316, 28]
https://chess.aronpetkovski.com/test/2542/
=> search.c: SEE Move Ordering

Source/search.c
bench: 954568
FINALLY IT PASSES
Elo   | 11.72 +- 6.12 (95%)
Games | N: 3854 W: 935 L: 805 D: 2114
Penta | [24, 421, 928, 509, 45]
https://chess.aronpetkovski.com/test/2601/
=> search.c: Add IIR

Source/search.c
bench: 4807135
Elo   | 3.73 +- 2.93 (95%)
Games | N: 17900 W: 4281 L: 4089 D: 9530
Penta | [191, 2087, 4215, 2253, 204]
https://chess.aronpetkovski.com/test/2708/
=> search.c: Add tuned parameters

Source/quanticade.c, Source/search.c, Source/transposition.c, Source/transposition.h, Source/uci.c
All nodes that match up the hash key will now have a hash move returned
Elo   | 4.65 +- 3.49 (95%)
LLR   | 2.94 (-2.94, 2.94) [0.00, 5.00]
Games | N: 13162 W: 3202 L: 3026 D: 6934
Penta | [163, 1516, 3066, 1654, 182]
https://chess.aronpetkovski.com/test/2765/
=> Refactor tt

Source/search.c
Elo   | 2.68 +- 2.15 (95%)
Games | N: 32808 W: 7751 L: 7498 D: 17559
Penta | [366, 3824, 7743, 4133, 338]
https://chess.aronpetkovski.com/test/2876/
=> Futility pruning

Source/search.c, Source/transposition.c, Source/transposition.h
Seems to be an 7% NPS speedup
bench: 4263236
Elo   | 5.66 +- 3.93 (95%)
Games | N: 9324 W: 2182 L: 2030 D: 5112
Penta | [89, 1022, 2286, 1178, 87]
https://chess.aronpetkovski.com/test/3051/
=> Source: Refactor probing TT code

Source/search.c
bench: 4698229
Elo   | 7.14 +- 4.52 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6956 W: 1668 L: 1525 D: 3763
Penta | [55, 759, 1726, 864, 74]
https://chess.aronpetkovski.com/test/3062/
=> search.c: Use tt_score as score if we have tt_hit

Source/search.c
bench: 5088404
Elo   | 4.63 +- 3.45 (95%)
Games | N: 12842 W: 3109 L: 2938 D: 6795
Penta | [129, 1492, 3027, 1625, 148]
https://chess.aronpetkovski.com/test/3083/
=> search.c: Init static eval based on check and tt_hit

Source/search.c, Source/transposition.c, Source/transposition.h
bench: 5088404
Elo   | 6.34 +- 4.26 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8444 W: 2064 L: 1910 D: 4470
Penta | [81, 967, 2003, 1059, 112]
https://chess.aronpetkovski.com/test/3111/
=> Source: TT Prefetch

Source/search.c
bench: 6429132
Elo   | 18.47 +- 7.51 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2184 W: 571 L: 455 D: 1158
Penta | [8, 203, 555, 317, 9]
https://chess.aronpetkovski.com/test/3287/
Elo   | 16.38 +- 7.55 (95%)
Games | N: 2866 W: 784 L: 649 D: 1433
Penta | [34, 294, 652, 409, 44]
https://chess.aronpetkovski.com/test/3285/
=> search.c: Use insertion sort for sorting moves

Source/search.c
bench: 6782351
unlikely for this to gain at this time control but it passes non reg with some 3elo gain (Small sample size)
Elo   | 2.99 +- 2.94 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 17772 W: 4294 L: 4141 D: 9337
Penta | [199, 2047, 4260, 2162, 218]
https://chess.aronpetkovski.com/test/3389/
=> search.c: Add variation to draw score

Source/search.c, Source/structs.h
bench: 7373737
Elo   | 0.38 +- 1.71 (95%)
Games | N: 53772 W: 13134 L: 13075 D: 27563
Penta | [649, 6497, 12504, 6618, 618]
https://chess.aronpetkovski.com/test/3797/
=> Source: Simplify 1 killer move

Source/search.c
Elo   | 0.26 +- 1.57 (95%)
LLR   | 2.99 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 62444 W: 15275 L: 15229 D: 31940
Penta | [704, 7536, 14692, 7590, 700]
https://chess.aronpetkovski.com/test/3833/
bench: 7617150
=> search.c: No NMP in pv nodes

Source/search.c
Elo   | 3.18 +- 2.55 (95%)
Games | N: 23948 W: 6037 L: 5818 D: 12093
Penta | [278, 2793, 5629, 2980, 294]
https://chess.aronpetkovski.com/test/3893/
bench: 7404097
=> search.c: Use static eval in the NMP reduction formula

Source/search.c
Elo   | 3.99 +- 3.27 (95%)
LLR   | 1.95 (-2.94, 2.94) [0.00, 3.00]
Games | N: 14536 W: 3671 L: 3504 D: 7361
Penta | [164, 1680, 3433, 1807, 184]
https://chess.aronpetkovski.com/test/3898/
bench: 7507145
=> search.c: Only do NMP if we have non pawns pieces

Source/search.c
Elo   | 3.46 +- 2.41 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 26088 W: 6512 L: 6252 D: 13324
Penta | [264, 3028, 6236, 3216, 300]
https://chess.aronpetkovski.com/test/3899/
bench: 7507161
=> search.c: LMP only if we have non pawn material

Source/search.c
SF style
Elo   | 8.95 +- 5.18 (95%)
Games | N: 5046 W: 1262 L: 1132 D: 2652
Penta | [22, 560, 1254, 640, 47]
https://chess.aronpetkovski.com/test/4128/
bench: 8444117
=> search.c: Double Extensions

Source/search.c
bench: 8444117
Elo   | 4.95 +- 4.11 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 9546 W: 2566 L: 2430 D: 4550
Penta | [113, 1118, 2195, 1214, 133]
https://chess.aronpetkovski.com/test/4379/
=> search.c: Simplify window_ok check

Source/search.c
bench: 8444117
Elo   | 14.05 +- 5.95 (95%)
SPRT  | 1.0+0.01s Threads=1 Hash=16MB
Games | N: 6162 W: 1957 L: 1708 D: 2497
Penta | [154, 662, 1249, 813, 203]
https://chess.aronpetkovski.com/test/4736/
=> search.c: Do not print unfinished asp window search

Source/search.c
Elo   | 0.69 +- 1.25 (95%)
LLR   | -0.84 (-2.25, 2.89) [0.00, 3.00]
Games | N: 103548 W: 26558 L: 26352 D: 50638
Penta | [1276, 12662, 23770, 12712, 1354]
https://chess.aronpetkovski.com/test/4797/
=> search.c: Use mate_score in FP check

Source/search.c
Elo   | 17.68 +- 6.05 (95%)
Games | N: 3974 W: 1102 L: 900 D: 1972
Penta | [22, 416, 934, 568, 47]
https://chess.aronpetkovski.com/test/5041/
Elo   | 22.75 +- 7.44 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 3610 W: 1143 L: 907 D: 1560
Penta | [51, 401, 727, 513, 113]
https://chess.aronpetkovski.com/test/5040/
bench: 4961444
=> search.c: Use values from latest LTC tune

Source/search.c, Source/structs.h
Elo   | 3.20 +- 3.57 (95%)
LLR   | 1.27 (-2.25, 2.89) [0.00, 3.00]
Games | N: 13668 W: 3588 L: 3462 D: 6618
Penta | [224, 1596, 3074, 1710, 230]
https://chess.aronpetkovski.com/test/5111/
bench: 4579273
=> Source: Make quiet history bigger

Source/search.c
Elo   | 5.33 +- 3.28 (95%)
Games | N: 16492 W: 4529 L: 4276 D: 7687
Penta | [267, 1932, 3626, 2123, 298]
https://chess.aronpetkovski.com/test/5159/
bench: 4958603
=> search.c: Add negative extensions

Source/search.c, Source/structs.h, Source/uci.c
Elo   | 3.74 +- 2.65 (95%)
Games | N: 26460 W: 7325 L: 7040 D: 12095
Penta | [515, 3077, 5769, 3346, 523]
https://chess.aronpetkovski.com/test/5193/
bench: 4720446
=> Source: Add capture history

Source/search.c
Elo   | 3.42 +- 2.44 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 3.00]
Games | N: 30336 W: 8357 L: 8058 D: 13921
Penta | [509, 3623, 6686, 3760, 590]
https://chess.aronpetkovski.com/test/5189/
bench: 4504346
=> search.c: Add cutnode negative extensions

Source/search.c
Elo   | 0.30 +- 1.62 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 58356 W: 14288 L: 14237 D: 29831
Penta | [610, 7070, 13812, 7031, 655]
https://chess.aronpetkovski.com/test/5461/
bench: 4505653
=> search.c: Promotions arent quiet moves

Source/search.c
Elo   | 1.53 +- 2.49 (95%)
LLR   | 3.02 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 24906 W: 6185 L: 6075 D: 12646
Penta | [277, 2953, 5906, 3017, 300]
https://chess.aronpetkovski.com/test/5499/
bench: 4375379
=> search.c: No promotion bonus for quiet moves

Source/search.c
Elo   | 0.02 +- 1.33 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 85812 W: 21193 L: 21187 D: 43432
Penta | [903, 10458, 20224, 10372, 949]
https://chess.aronpetkovski.com/test/5569/
bench: 4633799
=> search.c: LMR bigger limits

Source/search.c, Source/structs.h
Elo   | 3.29 +- 2.32 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 28060 W: 6913 L: 6647 D: 14500
Penta | [252, 3377, 6544, 3567, 290]
https://chess.aronpetkovski.com/test/5881/
bench: 4233111
=> Source: Bigger capture history

Source/search.c, Source/spsa.c
Elo   | 1.12 +- 0.77 (95%)
Games | N: 247700 W: 60213 L: 59414 D: 128073
Penta | [2424, 29573, 59072, 30342, 2439]
https://chess.aronpetkovski.com/test/5903/
Thats one insane test.....
=> Lmr capt hist

Source/search.c
Elo   | 2.68 +- 1.97 (95%)
Games | N: 31660 W: 7044 L: 6800 D: 17816
Penta | [88, 3705, 8018, 3913, 106]
https://chess.aronpetkovski.com/test/6370/
=> search.c: Triple extensions

Source/search.c
Elo   | 6.55 +- 3.49 (95%)
LLR   | 3.02 (-2.25, 2.89) [0.00, 3.00]
Games | N: 11932 W: 3017 L: 2792 D: 6123
Penta | [95, 1362, 2845, 1551, 113]
https://chess.aronpetkovski.com/test/6451/
=> search.c: 2ply conthist

Source/search.c
Elo   | 4.77 +- 2.95 (95%)
Games | N: 16530 W: 4041 L: 3814 D: 8675
Penta | [133, 1913, 3953, 2126, 140]
https://chess.aronpetkovski.com/test/6461/
=> Promotions on top of move list

Source/search.c
Elo   | 8.48 +- 4.10 (95%)
Games | N: 8442 W: 2115 L: 1909 D: 4418
Penta | [62, 925, 2058, 1097, 79]
https://chess.aronpetkovski.com/test/6503/
=> search.c: Change RFP return

Source/search.c, Source/structs.h, Source/uci.c, Source/uci.h
Elo   | 21.35 +- 6.30 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
Games | N: 2998 W: 709 L: 525 D: 1764
Penta | [4, 278, 757, 450, 10]
https://chess.aronpetkovski.com/test/6801/
Elo   | 23.38 +- 6.81 (95%)
Games | N: 2828 W: 758 L: 568 D: 1502
Penta | [9, 262, 697, 422, 24]
https://chess.aronpetkovski.com/test/6800/
Based on Alexandria implementation
=> Source: Add best move tm

Source/search.c, Source/uci.c, Source/uci.h
Elo   | 2.93 +- 2.09 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 29286 W: 6506 L: 6259 D: 16521
Penta | [131, 3373, 7413, 3570, 156]
https://chess.aronpetkovski.com/test/6809/
=> Source: Add eval stability TM

Source/search.c
Elo   | 2.70 +- 1.96 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 32318 W: 7081 L: 6830 D: 18407
Penta | [122, 3710, 8254, 3941, 132]
https://chess.aronpetkovski.com/test/6962/
=> search.c: Dont do IIR in excluded search

Source/search.c
Elo   | 2.23 +- 1.71 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 42700 W: 9273 L: 8999 D: 24428
Penta | [185, 4892, 10920, 5170, 183]
https://chess.aronpetkovski.com/test/6960/
=> search.c: RFP return mid

Source/search.c
```Elo   | 3.22 +- 3.17 (95%)
Games | N: 12304 W: 2732 L: 2618 D: 6954
Penta | [37, 1424, 3131, 1508, 52]```
<https://chess.aronpetkovski.com/test/7374/>
=> search.c: Remove beta condition in full LMR window

Source/search.c, Source/structs.h
Elo   | -1.82 +- 1.88 (95%)
LLR   | -2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 36392 W: 8048 L: 8239 D: 20105
Penta | [180, 4455, 9108, 4282, 171]
<https://chess.aronpetkovski.com/test/7400/>
Does it look like its failing ? YES. I dont care anymore. This thing is GONE from quanticade.
No more being afraid to touch PV cause it changed bench.
=> TT probe at root node and remove PV scoring

Source/search.c
Elo   | 1.69 +- 1.37 (95%)
Games | N: 69810 W: 15769 L: 15430 D: 38611
Penta | [336, 8294, 17343, 8559, 373]
<https://chess.aronpetkovski.com/test/7410/>
=> search.c: Reduce less if TT move depth is equal or better than depth

Source/search.c
Elo   | 2.03 +- 1.62 (95%)
Games | N: 52096 W: 12117 L: 11813 D: 28166
Penta | [323, 6180, 12781, 6398, 366]
<https://chess.aronpetkovski.com/test/7442/>
=> search.c: Update capthist in QS

Source/search.c
Elo   | 2.62 +- 1.96 (95%)
Games | N: 34194 W: 7804 L: 7546 D: 18844
Penta | [187, 3942, 8587, 4188, 193]
<https://chess.aronpetkovski.com/test/7485/>
=> search.c: Add depth limit to NMP

Source/search.c
Elo   | 1.01 +- 2.05 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 30730 W: 6998 L: 6909 D: 16823
Penta | [154, 3603, 7771, 3674, 163]
<https://chess.aronpetkovski.com/test/7543/>
=> search.c: Refactor the way check extensions are done

Source/history.c, Source/search.c
Elo   | 2.07 +- 1.62 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 3.00]
Games | N: 49592 W: 11438 L: 11142 D: 27012
Penta | [224, 5876, 12358, 6056, 282]
<https://chess.aronpetkovski.com/test/7582/>
=> 4ply conthist

Source/search.c
Elo   | 2.16 +- 1.70 (95%)
Games | N: 44846 W: 10220 L: 9941 D: 24685
Penta | [224, 5190, 11340, 5421, 248]
<https://chess.aronpetkovski.com/test/7909/>
This was thought by me but sadly not original as it was already in SF and even simplified away...
=> search.c: Do more NE if move is not pvnode

Source/search.c
Elo   | 3.37 +- 2.27 (95%)
Games | N: 21856 W: 4584 L: 4372 D: 12900
Penta | [41, 2380, 5869, 2602, 36]
<https://chess.aronpetkovski.com/test/7911/>
=> search.c: DE in pv_node with margin

Source/enums.h, Source/search.c
Elo   | 1.17 +- 2.17 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 27044 W: 5996 L: 5905 D: 15143
Penta | [135, 3142, 6867, 3253, 125]
<https://chess.aronpetkovski.com/test/8054/>
Should also gain but non reg is easier to test.
=> Source: Find PV nodes correctly not by a hack

Source/search.c
Elo   | 0.90 +- 1.11 (95%)
LLR   | 0.57 (-2.25, 2.89) [0.00, 3.00]
Games | N: 103744 W: 22925 L: 22655 D: 58164
Penta | [453, 12369, 25992, 12571, 487]
<https://chess.aronpetkovski.com/test/8085/>
Not finished but at this point i would say that its clear gainer and Obsidian Dev agrees
=> search.c: Reduce less if TT move was PV node

Source/search.c
Elo   | 3.38 +- 3.26 (95%)
Games | N: 11916 W: 2657 L: 2541 D: 6718
Penta | [43, 1378, 3014, 1466, 57]
<https://chess.aronpetkovski.com/test/8103/>
=> search.c: Store tt_was_pv into TT instead of pv_node

Source/search.c
Elo   | 3.38 +- 3.26 (95%)
Games | N: 11916 W: 2657 L: 2541 D: 6718
Penta | [43, 1378, 3014, 1466, 57]
<https://chess.aronpetkovski.com/test/8103/>
=> search.c: Use a parameter for pv_node in QS

Source/search.c
Elo   | 2.76 +- 2.04 (95%)
Games | N: 31676 W: 7241 L: 6989 D: 17446
Penta | [160, 3719, 7866, 3895, 198]
<https://chess.aronpetkovski.com/test/8110/>
=> search.c: Do more LMP

Source/search.c
Elo   | 1.86 +- 1.50 (95%)
Games | N: 57942 W: 13181 L: 12870 D: 31891
Penta | [293, 6776, 14521, 7089, 292]
<https://chess.aronpetkovski.com/test/8118/>
=> search.c: LMP in check

Source/search.c
Elo   | 1.03 +- 1.59 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 0.67 (-2.25, 2.89) [0.00, 3.00]
Games | N: 43744 W: 9145 L: 9015 D: 25584
Penta | [59, 4891, 11863, 4979, 80]
<https://chess.aronpetkovski.com/test/8119/>
Running for WAY too long with always positive LLR. Lets just merge.
=> search.c: lmr reductions more if not PV node for lmr_depth

Source/search.c, Source/transposition.c, Source/transposition.h
Elo   | 0.28 +- 1.49 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 58394 W: 13176 L: 13129 D: 32089
Penta | [328, 6905, 14615, 7090, 259]
<https://chess.aronpetkovski.com/test/8194/>
WDYM this should gain at STC ? This is very clearly a HUGE scaller....
=> Source: Refactor and fix TT score usage

Source/search.c
Elo   | 0.06 +- 1.25 (95%)
Games | N: 78746 W: 17836 L: 17823 D: 43087
Penta | [366, 8975, 20696, 8952, 384]
<https://chess.aronpetkovski.com/test/8145/>
=> search.c: Do not extend if our ply is > 2*rootdepth

Source/nnue.c, Source/nnue.h, Source/search.c
Elo   | 9.65 +- 4.14 (95%)
Games | N: 6590 W: 1478 L: 1295 D: 3817
Penta | [14, 647, 1801, 808, 25]
<https://chess.aronpetkovski.com/test/8247/>
=> Source: Make king buckets refresh only 1 side of accumulator

Source/bitboards.h, Source/search.c, Source/structs.h, Source/transposition.c, Source/transposition.h
```Elo   | 4.29 +- 2.75 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 3.09 (-2.25, 2.89) [0.00, 3.00]
Games | N: 21766 W: 5839 L: 5570 D: 10357
Penta | [287, 2554, 4957, 2773, 312]```
<https://chess.aronpetkovski.com/test/8491/>
=> Static eval tt

Source/search.c
Elo   | 3.59 +- 3.42 (95%)
Games | N: 11526 W: 2788 L: 2669 D: 6069
Penta | [69, 1334, 2848, 1433, 79]
<https://chess.aronpetkovski.com/test/8584/>
=> search.c: Fix stack in QS

Source/search.c
Elo   | 1.09 +- 1.43 (95%)
LLR   | 0.84 (-2.25, 2.89) [0.00, 3.00]
Games | N: 68048 W: 16381 L: 16167 D: 35500
Penta | [515, 7990, 16814, 8176, 529]
<https://chess.aronpetkovski.com/test/8640/>
As Gabe would say. Screw this. Im merging.
=> search.c: SEE history score modifier

Source/search.c
Elo   | 37.48 +- 8.96 (95%)
Games | N: 1880 W: 551 L: 349 D: 980
Penta | [10, 152, 439, 304, 35]
<https://chess.aronpetkovski.com/test/8760/>
=> search.c: Skip moves with bad SEE score in QS

Source/search.c
Elo   | 1.92 +- 1.55 (95%)
Games | N: 58000 W: 14195 L: 13875 D: 29930
Penta | [402, 6855, 14211, 7085, 447]
<https://chess.aronpetkovski.com/test/8761/>
=> search.c: QS FP

Source/search.c
Elo   | 1.11 +- 2.16 (95%)
Games | N: 28850 W: 6711 L: 6619 D: 15520
Penta | [165, 3455, 7109, 3515, 181]
<https://chess.aronpetkovski.com/test/8805/>
Finally we get rid of it
=> search.c: Do not extend reduced_depth

Source/search.c
Elo   | 2.73 +- 2.01 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 32620 W: 7647 L: 7391 D: 17582
Penta | [188, 3741, 8208, 3973, 200]
<https://chess.aronpetkovski.com/test/8921/>
=> search.c: Order non capture promotions below good capture promotions

Source/search.c
Elo   | 2.63 +- 1.96 (95%)
Games | N: 33780 W: 7753 L: 7497 D: 18530
Penta | [173, 3923, 8440, 4183, 171]
<https://chess.aronpetkovski.com/test/8922/>
=> search.c: tt_pv failed low lmr reduction

Source/search.c, Source/structs.h
Elo   | 0.19 +- 1.41 (95%)
Games | N: 64306 W: 14368 L: 14333 D: 35605
Penta | [304, 7603, 16301, 7644, 301]
<https://chess.aronpetkovski.com/test/8984/>
=> Source: tt_pv on stack for excluded moves

Source/search.c
Elo   | 5.42 +- 3.10 (95%)
Games | N: 13084 W: 3030 L: 2826 D: 7228
Penta | [48, 1470, 3310, 1658, 56]
https://furybench.com/test/143/
=> search.c: Use ss->eval in NMP

Source/search.c
Elo   | 2.87 +- 2.07 (95%)
Games | N: 29552 W: 6695 L: 6451 D: 16406
Penta | [112, 3450, 7442, 3626, 146]
https://furybench.com/test/188/
=> search.c: Use 1ply conthist in search quiet hist score

Source/search.c
Elo   | 1.01 +- 1.25 (95%)
LLR   | 0.83 (-2.25, 2.89) [0.00, 3.00]
Games | N: 84254 W: 19399 L: 19154 D: 45701
Penta | [458, 9998, 20991, 10201, 479]
https://furybench.com/test/203/
as mr gabe would say. just merge it already.
the chance of this losing elo crazily low and it probably scales...
=> search.c: use 2ply conthist in search hist score

Source/search.c
Elo   | 1.75 +- 2.48 (95%)
LLR   | 2.99 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 20822 W: 4710 L: 4605 D: 11507
Penta | [104, 2421, 5243, 2552, 91]
https://furybench.com/test/230/
i can finally do this and it doesnt lose elo but seems to be actually good.
=> search.c: Use stack static eval for improving

Source/search.c
Elo   | 2.80 +- 2.02 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 3.00]
Games | N: 31312 W: 7211 L: 6959 D: 17142
Penta | [144, 3618, 7891, 3848, 155]
https://furybench.com/test/260/
=> search.c: LMR do deeper and shallower

Source/search.c
Elo   | 3.02 +- 3.18 (95%)
Games | N: 13330 W: 3244 L: 3128 D: 6958
Penta | [77, 1559, 3292, 1645, 92]
https://furybench.com/test/469/
=> search.c: Use improving_factor in improving LMP

Source/history.c
Elo   | 7.38 +- 4.67 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 5742 W: 1371 L: 1249 D: 3122
Penta | [25, 612, 1477, 730, 27]
https://furybench.com/test/595/
=> history.c: Linear history

Source/search.c
Elo   | 4.06 +- 2.59 (95%)
Games | N: 18384 W: 4208 L: 3993 D: 10183
Penta | [64, 2072, 4707, 2283, 66]
https://furybench.com/test/879/
=> search.c: Add constant margin offset to RFP

Source/search.c
Elo   | 1.01 +- 1.41 (95%)
LLR   | 0.73 (-2.25, 2.89) [0.00, 3.00]
Games | N: 60978 W: 13762 L: 13585 D: 33631
Penta | [183, 7092, 15771, 7251, 192]
https://furybench.com/test/887/
this was 10+-5 and passed 0 5 bounds already
=> search.c: Qsearch LMP

Source/search.c
Elo   | 1.12 +- 1.29 (95%)
LLR   | 1.23 (-2.25, 2.89) [0.00, 3.00]
Games | N: 74742 W: 16869 L: 16629 D: 41244
Penta | [298, 8660, 19193, 8944, 276]
https://furybench.com/test/909/
as mr obsidian would say. Merge it...
=> search.c: static eval NMP

Source/history.c, Source/search.c
Elo   | 0.12 +- 1.30 (95%)
LLR   | 2.93 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 72100 W: 15990 L: 15966 D: 40144
Penta | [233, 8500, 18561, 8522, 234]
https://furybench.com/test/1009/
=> Source: Handle enpassant correctly in capture history

Source/search.c
Elo   | 3.47 +- 2.34 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 22712 W: 5157 L: 4930 D: 12625
Penta | [67, 2638, 5735, 2833, 83]
https://furybench.com/test/1038/
=> search.c: Use improving lmp if static eval is bigger than beta

Source/uci.c
This should fix the time losses
Loses elo at STC:
Elo   | -5.63 +- 3.96 (95%)
LLR   | -2.28 (-2.25, 2.89) [0.00, 3.00]
Games | N: 7038 W: 1591 L: 1705 D: 3742
Penta | [23, 806, 1971, 700, 19]
https://furybench.com/test/1514/
Seems to be a maybe slight gainer at LTC:
Elo   | 0.99 +- 1.56 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 0.67 (-2.25, 2.89) [0.00, 3.00]
Games | N: 37690 W: 8133 L: 8026 D: 21531
Penta | [27, 3584, 11520, 3683, 31]
https://furybench.com/test/1515/
Thus it scales and we merging :)
=> uci.c: Simplify TM and improve it

Source/search.c
Elo   | 4.15 +- 2.64 (95%)
Games | N: 17900 W: 4185 L: 3971 D: 9744
Penta | [64, 2030, 4558, 2224, 74]
https://furybench.com/test/1546/
=> search.c: Adjust FP margin with history

Source/search.c
Elo   | 0.42 +- 1.58 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 48490 W: 11197 L: 11138 D: 26155
Penta | [175, 5601, 12641, 5646, 182]
https://furybench.com/test/1597/
=> search.c: Score moves based on TT move in QS

Source/history.c, Source/search.c, Source/structs.h
Elo   | 6.29 +- 4.29 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 2.78 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 6078 W: 1370 L: 1260 D: 3448
Penta | [7, 649, 1619, 755, 9]
https://furybench.com/test/1798/
=> Source: Smaller pawnhist

Source/search.c
Elo   | 6.62 +- 3.42 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 10338 W: 2487 L: 2290 D: 5561
Penta | [27, 1117, 2706, 1270, 49]
https://furybench.com/test/1951/
=> search.c: Reduce less if move gives a check

Source/evaluate.c, Source/history.c
Elo   | 1.53 +- 2.36 (95%)
Games | N: 22254 W: 5189 L: 5091 D: 11974
Penta | [61, 2666, 5602, 2710, 88]
https://furybench.com/test/2001/
=> Source: Move fifty move rule scaling to static eval adjusting

Source/search.c
Elo   | 1.64 +- 1.33 (95%)
Games | N: 70028 W: 16612 L: 16282 D: 37134
Penta | [206, 8282, 17781, 8466, 279]
https://furybench.com/test/2567/
=> search.c: Adjust fail high return score in main search

Source/history.c, Source/history.h, Source/search.c, Source/structs.h
Elo   | 0.61 +- 0.97 (95%)
LLR   | -0.17 (-2.25, 2.89) [0.00, 2.50]
Games | N: 128018 W: 30029 L: 29806 D: 68183
Penta | [339, 15118, 32927, 15231, 394]
https://furybench.com/test/2542/
I say good enough and with tune it has to be good
=> Source: Update quiet history on TT cutoff

Source/search.c
Elo   | 0.89 +- 1.97 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 32332 W: 7827 L: 7744 D: 16761
Penta | [132, 3798, 8209, 3909, 118]
https://furybench.com/test/2605/
=> search.c: Do hindsight depth modifications before premove pruning check

Source/search.c, Source/structs.h
Elo   | 0.53 +- 1.41 (95%)
LLR   | -0.69 (-2.25, 2.89) [0.00, 3.00]
Games | N: 60420 W: 14013 L: 13921 D: 32486
Penta | [149, 7188, 15429, 7310, 134]
https://furybench.com/test/2620/
=> Source: Implement cutoff cnt reductions

Source/search.c, Source/structs.h
Elo   | 1.96 +- 2.54 (95%)
Games | N: 17918 W: 4161 L: 4060 D: 9697
Penta | [26, 2070, 4678, 2147, 38]
https://furybench.com/test/2685/
=> Source: Add NMP verification search

Source/search.c
Elo   | 1.89 +- 1.52 (95%)
Games | N: 54300 W: 12918 L: 12622 D: 28760
Penta | [213, 6303, 13828, 6587, 219]
https://furybench.com/test/2864/
=> search.c: Allow extensions in LMR if in cutnode

Source/search.c
Elo   | 6.07 +- 4.01 (95%)
LLR   | 3.21 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 7494 W: 1833 L: 1702 D: 3959
Penta | [17, 830, 1932, 941, 27]
https://furybench.com/test/3065/
=> search.c: Use static eval when checking if we can use tt_score

Source/search.c
Elo   | 2.86 +- 2.94 (95%)
Games | N: 12774 W: 3001 L: 2896 D: 6877
Penta | [31, 1347, 3522, 1460, 27]
https://furybench.com/test/3127/
=> search.c: Dont treat promotions as non quiet in SEE

Source/search.c, Source/structs.h
Elo   | -0.12 +- 0.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 119220 W: 27827 L: 27868 D: 63525
Penta | [333, 12992, 32971, 13011, 303]
https://furybench.com/test/3159/
=> Source: Init and set piece to NO_PIECE in NMP
