Quanticade/Quanticade

Source/search.c
Source/utils.h

Elo   | 0.41 +- 2.20 (95%)
LLR   | -3.04 (-2.94, 2.94) [0.00, 5.00]
Games | N: 39502 W: 12149 L: 12102 D: 15251
Penta | [929, 4416, 8998, 4495, 913]
Does not gain but passes non regression LLR with these games and bounds

Fixed move ordering

---

Source/nnue.c

Elo   | 11.70 +- 5.98 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3980 W: 983 L: 849 D: 2148
Penta | [28, 420, 974, 526, 42]
Elo   | 11.65 +- 6.33 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4386 W: 1226 L: 1079 D: 2081
Penta | [63, 483, 979, 580, 88]

nnue.c: Fused updates

---

Source/nnue.c

bench: 4064696
Elo   | 1.28 +- 3.24 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 15184 W: 3925 L: 3869 D: 7390
Penta | [205, 1740, 3664, 1760, 223]

nnue.c: Add inline to clamp

---

Source/movegen.c

no functional update
bench: 4064696

movegen.c: Tiny refactor on make_move

---

Source/search.c

No functional change
bench: 4000972

search.c: Fix mate reporting from white perspective

---

Source/movegen.c
Source/movegen.h
Source/search.c
Source/structs.h

Elo   | 5.06 +- 3.72 (95%)
Games | N: 11948 W: 3195 L: 3021 D: 5732
Penta | [164, 1367, 2764, 1489, 190]
https://chess.aronpetkovski.com/test/1969/

History maluses

---

Source/movegen.c
Source/pvtable.c
Source/quanticade.c
Source/search.c
Source/structs.h

No functional change
bench: 3284648

Source: Move keys to global

---

Source/search.c

Elo   | 0.27 +- 2.57 (95%)
LLR   | 2.98 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 24258 W: 6096 L: 6077 D: 12085
Penta | [309, 2946, 5610, 2945, 319]
bench: 2698808

search.c: Only update PV in PV nodes

---

Source/search.c

Elo   | 3.12 +- 2.50 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 26146 W: 6749 L: 6514 D: 12883
Penta | [336, 3114, 5984, 3257, 382]
https://chess.aronpetkovski.com/test/2130/
bench: 2284430
inspired by Elixir

search.c: Refactor razoring and increase depth its done to

---

Source/search.c

Most likely NMP parameters are still WRONG.
bench: 2036983

search.c: First SPSA tune

---

Source/search.c

Elo   | -0.02 +- 2.24 (95%)
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 29106 W: 6350 L: 6352 D: 16404
Penta | [259, 3505, 7070, 3417, 302]
https://chess.aronpetkovski.com/test/2406/
passes non reg
bench: 5479347

search.c: Add mate distance pruning

---

Makefile
Source/nnue.c
Source/nnue.h
Source/quanticade.c
Source/simd.h
Source/structs.h

Elo   | 27.94 +- 9.65 (95%)
LLR   | 3.13 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1670 W: 452 L: 318 D: 900
Penta | [10, 161, 377, 259, 28]
https://chess.aronpetkovski.com/test/2445/
bench: 5479347
Inspired by Elixir implementation

Quanticade: SIMD

---

Source/search.c

Doesnt change the bench. Doesnt speed up anything yet it gains....
Elo   | 2.75 +- 2.20 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 30520 W: 6870 L: 6628 D: 17022
Penta | [294, 3512, 7442, 3682, 330]
https://chess.aronpetkovski.com/test/2458/
bench: 5479347

search.c: Add material draw

---

Source/search.c

bench: 4357352
Elo   | 17.77 +- 7.76 (95%)
Games | N: 2524 W: 621 L: 492 D: 1411
Penta | [24, 250, 592, 365, 31]
https://chess.aronpetkovski.com/test/2541/

search.c: Add SEE PVS

---

Source/search.c

bench: 4424530
Elo   | 18.87 +- 7.94 (95%)
Games | N: 2304 W: 565 L: 440 D: 1299
Penta | [19, 215, 570, 318, 30]
https://chess.aronpetkovski.com/test/2544/

search.c: Qsearch SEE Pruning

---

Source/search.c

Elo   | 10.80 +- 5.87 (95%)
Games | N: 4344 W: 1099 L: 964 D: 2281
Penta | [44, 455, 1043, 582, 48]
https://chess.aronpetkovski.com/test/2688/

Refactor lmr

---

Source/evaluate.c

Elo   | 5.15 +- 3.71 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 11202 W: 2672 L: 2506 D: 6024
Penta | [137, 1252, 2641, 1450, 121]
https://chess.aronpetkovski.com/test/2790/
Who am i to complain about 5 elo ? LOL

Material scale

---

Source/bitboards.h
Source/structs.h

Elo   | 4.57 +- 2.88 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 18314 W: 4337 L: 4096 D: 9881
Penta | [197, 2074, 4386, 2291, 209]
https://chess.aronpetkovski.com/test/2941/

Source: TT score to 16bits

---

Source/structs.h
Source/transposition.c

Elo   | 8.26 +- 4.08 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=1MB
Games | N: 9254 W: 2236 L: 2016 D: 5002
Penta | [91, 1039, 2174, 1205, 118]
https://chess.aronpetkovski.com/test/2955/

12bytes tt

---

Makefile
Source/search.c
Source/transposition.c
Source/transposition.h

Elo   | 7.49 +- 4.66 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6684 W: 1591 L: 1447 D: 3646
Penta | [56, 739, 1619, 861, 67]
https://chess.aronpetkovski.com/test/3002/

Read tt refactor

---

Source/search.c

bench: 6023908
Elo   | 3.72 +- 2.92 (95%)
Games | N: 18416 W: 4692 L: 4495 D: 9229
Penta | [223, 2120, 4336, 2295, 234]
https://chess.aronpetkovski.com/test/3282/

search.c: Move ordering based on promotions

---

Source/bitboards.h
Source/evaluate.c
Source/evaluate.h
Source/movegen.c
Source/nnue.c
Source/nnue.h
Source/perft.c
Source/search.c
Source/structs.h
Source/uci.c

bench: 7362893
Elo   | 9.01 +- 5.23 (95%)
LLR   | 3.09 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5788 W: 1496 L: 1346 D: 2946
Penta | [69, 623, 1376, 741, 85]
https://chess.aronpetkovski.com/test/3755/

Source: Implement accumulator stack

---

Source/bitboards.h
Source/evaluate.c
Source/evaluate.h
Source/movegen.c
Source/nnue.c
Source/nnue.h
Source/perft.c
Source/search.c
Source/structs.h
Source/threads.c
Source/uci.c

Elo   | 25.76 +- 7.57 (95%)
SPRT  | 4.0+0.04s Threads=2 Hash=64MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 2946 W: 895 L: 677 D: 1374
Penta | [36, 271, 661, 449, 56]
https://chess.aronpetkovski.com/test/4759/
Elo   | 11.99 +- 5.04 (95%)
LLR   | 2.96 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6318 W: 1742 L: 1524 D: 3052
Penta | [65, 695, 1456, 843, 100]
https://chess.aronpetkovski.com/test/4757/

Implement accumulator stack

---

Source/search.c
Source/uci.c

Elo   | 16.50 +- 6.11 (95%)
Games | N: 4678 W: 1336 L: 1114 D: 2228
Penta | [53, 514, 1033, 636, 103]
https://chess.aronpetkovski.com/test/4830/
Elo   | 12.11 +- 4.95 (95%)
Games | N: 5914 W: 1520 L: 1314 D: 3080
Penta | [41, 644, 1397, 818, 57]
https://chess.aronpetkovski.com/test/4833/

Asp windows proper

---

Source/quanticade.c
Source/spsa.c
Source/spsa.h
Source/structs.h
Source/uci.c

No more billions of else if for every single SPSA variable. Simple, effective system that can easily scale to our needs
bench: 6536008

Source: Completely rework SPSA system

---

Source/search.c
Source/structs.h

No functional change
bench: 4285798

search.c: Stack history score

---

.github/workflows/c-cpp.yml

Use clang with CI

---

Source/uci.c

Elo   | 14.15 +- 5.38 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 3.00]
Games | N: 5062 W: 1299 L: 1093 D: 2670
Penta | [32, 541, 1211, 683, 64]
https://chess.aronpetkovski.com/test/6049/
Thanks to Alexandria chess engine for the parameters

uci.c: Use TM parameters from Alexandria

---

Source/spsa.c
Source/uci.c

I mean doesnt really need SPRT cause it cannot make TM worse....

Safety gui margin

---

Source/search.c
Source/structs.h
Source/uci.c

Doesnt solve it but it cannot hurt

Source: Fix a bug causing timeout if time = 0

---

Source/nnue.c
Source/nnue.h
Source/search.c

Elo   | 10.00 +- 4.35 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 6982 W: 1743 L: 1542 D: 3697
Penta | [39, 723, 1786, 884, 59]
https://chess.aronpetkovski.com/test/6193/
bench 4223374

Speedup Accumulator Makemove

---

Source/search.c

Elo   | 1.91 +- 1.52 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 62624 W: 14877 L: 14533 D: 33214
Penta | [482, 7518, 15058, 7682, 572]
https://chess.aronpetkovski.com/test/6210/
OMG IT GAINS FINALY

search.c: Lets try improving again

---

Source/bitboards.h
Source/search.c

NO_SCORE improving check

---

Source/bitboards.h
Source/history.c
Source/history.h
Source/move.c
Source/move.h
Source/movegen.c
Source/nnue.c
Source/perft.c
Source/quanticade.c
Source/search.c
Source/structs.h
Source/uci.c

This is like an 1elo loss but the gains from the TT size getting smaller with 16bit hash key should bring elo

Move to uint16_t

---

Source/transposition.c

transposition.c: Make index for prefetching 64bit

---

Source/search.c
Source/threads.c
Source/threads.h

Elo   | 0.92 +- 2.05 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 33636 W: 7916 L: 7827 D: 17893
Penta | [249, 4072, 8126, 4083, 288]
https://chess.aronpetkovski.com/test/6778/

Fix some TM issues

---

Source/search.c

Elo   | 4.25 +- 3.61 (95%)
Games | N: 9718 W: 2136 L: 2017 D: 5565
Penta | [42, 1089, 2485, 1194, 49]
https://chess.aronpetkovski.com/test/7107/

search.c: QS above TT probe

---

Source/uci.c

uci.c: Clear cont hist on ucinewgame

---

Source/search.c
Source/transposition.h

Elo   | 0.94 +- 1.98 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 31882 W: 6864 L: 6778 D: 18240
Penta | [125, 3736, 8137, 3814, 129]```
<https://chess.aronpetkovski.com/test/7179/>

Source: Refactor hash flags

---

Source/search.c

Elo   | -0.10 +- 0.99 (95%)
LLR   | 3.02 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 114482 W: 24608 L: 24641 D: 65233
Penta | [378, 12354, 31840, 12261, 408]
<https://chess.aronpetkovski.com/test/7186/>

search.c: Possible fix for old bug

---

Source/search.c
Source/structs.h
Source/uci.c

Elo   | 0.39 +- 1.44 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 0.00]
Games | N: 51526 W: 11006 L: 10948 D: 29572
Penta | [150, 5299, 14827, 5317, 170]
<https://chess.aronpetkovski.com/test/7234/>

Node limit

---

Source/history.c
Source/history.h
Source/search.c
Source/see.c
Source/see.h

Source: Refactor some stuff

---

Source/search.c

search.c: Check that move is legal before going to SE

---

Source/search.c

Elo   | 2.62 +- 1.97 (95%)
Games | N: 35518 W: 8544 L: 8276 D: 18698
Penta | [247, 4163, 8670, 4433, 246]
<https://chess.aronpetkovski.com/test/8471/>
bench: 4635064

search.c: RFP improving

---

Source/search.c
Source/transposition.c
Source/transposition.h

Source: Use tt_entry pointer in write TT

---

Source/nnue.c
Source/nnue.h
Source/structs.h
Source/uci.c

Elo   | 28.57 +- 7.52 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 3.00]
Games | N: 2340 W: 675 L: 483 D: 1182
Penta | [8, 196, 589, 350, 27]
<https://chess.aronpetkovski.com/test/8702/>

Finny tables

---

Source/nnue.c

Elo   | 3.77 +- 2.47 (95%)
Games | N: 19622 W: 4705 L: 4492 D: 10425
Penta | [83, 2071, 5310, 2244, 103]
<https://chess.aronpetkovski.com/test/8703/>

nnue.c: Fuse finny table updates

---

Source/search.c

Elo   | 4.79 +- 3.00 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 17694 W: 4696 L: 4452 D: 8546
Penta | [194, 2089, 4095, 2217, 252]
<https://chess.aronpetkovski.com/test/8741/>

search.c: QS evasions

---

Source/search.c

Elo   | 16.60 +- 6.00 (95%)
Games | N: 4316 W: 1187 L: 981 D: 2148
Penta | [35, 466, 968, 636, 53]
<https://chess.aronpetkovski.com/test/8750/>

search.c: Save to TT in QS

---

Source/search.c

Elo   | 1.59 +- 2.20 (95%)
LLR   | 1.00 (-2.25, 2.89) [0.00, 3.00]
Games | N: 30366 W: 7611 L: 7472 D: 15283
Penta | [281, 3575, 7359, 3660, 308]
<https://chess.aronpetkovski.com/test/8756/>
This would have passed nonreg already

search.c: Save and score TT move in QS

---

Source/search.c
Source/structs.h
Source/uci.c

Elo   | 4.60 +- 3.78 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 9066 W: 2249 L: 2129 D: 4688
Penta | [69, 926, 2425, 1042, 71]
<https://chess.aronpetkovski.com/test/8862/>

Source: move repetitions into thread

---

Source/bitboards.h
Source/movegen.c
Source/search.c
Source/structs.h

Elo   | -0.53 +- 1.09 (95%)
LLR   | -0.14 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 99428 W: 22288 L: 22439 D: 54701
Penta | [484, 10949, 26949, 10898, 434]
<https://chess.aronpetkovski.com/test/8918/>
Its maybe a tiny tiny slowdown but should be fine

Copy board removal

---

Source/transposition.c
Source/uci.c

Not a slowdown and didnt change bench.

Source: Multithreaded TT clearing

---

Source/search.c

Elo   | 6.71 +- 3.52 (95%)
Games | N: 10356 W: 2458 L: 2258 D: 5640
Penta | [50, 1135, 2604, 1343, 46]
<https://chess.aronpetkovski.com/test/8986/>
Should be speedup elo but penta scaler 👀

search.c: Implement basic move picker

---

Source/structs.h
Source/transposition.c
Source/transposition.h

dark times ahead. furybench is down. but this passed

Source: Do buckets with 16bit key and 3 entries per bucket

---

Source/nnue.c

Elo   | 0.56 +- 1.63 (95%)
LLR   | 3.05 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 43326 W: 9684 L: 9614 D: 24028
Penta | [159, 4706, 11872, 4758, 168]
https://furybench.com/test/17/

nnue.c: Cleanup the NNUE code a little

---

Source/search.c

Elo   | 2.19 +- 1.72 (95%)
Games | N: 46872 W: 11232 L: 10937 D: 24703
Penta | [308, 5557, 11472, 5730, 369]
https://furybench.com/test/457/

search.c: Try new LMP margin formula

---

Source/nnue.c

```
after                |               before               |
mu              sigma       |        mu              sigma       |   Sp(1)/Sp(2)      3*sigma
------------------------------------+------------------------------------+------------------------------------
1898000.000             0.000|       1787000.000             0.000|       6.212 %  +/-  0.000 %
1882500.000         15500.000|       1788500.000          1500.000|       5.257 %  +/-  2.865 %
1889333.333         11259.564|       1789000.000          1000.000|       5.609 %  +/-  1.962 %
1886750.000          8370.335|       1794750.000          5793.315|       5.131 %  +/-  1.995 %
1886800.000          6483.826|       1798000.000          5540.758|       4.944 %  +/-  1.644 %
1888666.667          5613.476|       1799833.333 …
```

bench: 3201382

---

Source/movegen.c
Source/movegen.h
Source/search.c

Elo   | 0.65 +- 1.78 (95%)
LLR   | 2.98 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 40378 W: 9477 L: 9402 D: 21499
Penta | [207, 4686, 10342, 4733, 221]
https://furybench.com/test/557/

Source: Fix qsearch movegen

---

Source/nnue.h

Elo   | 1.70 +- 1.38 (95%)
Games | N: 65692 W: 15364 L: 15043 D: 35285
Penta | [238, 7677, 16719, 7950, 262]
https://furybench.com/test/1503/

nnue.h: Increase L1 quant to 128

---

Source/nnue.h

Elo   | 4.60 +- 2.78 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 15800 W: 3715 L: 3506 D: 8579
Penta | [41, 1796, 4036, 1967, 60]
https://furybench.com/test/1696/

nnue.h: Make L1 values in range of 0-255

---

Source/attacks.c
Source/attacks.h
Source/history.c
Source/search.c
Source/structs.h
Source/uci.c

Elo   | 11.38 +- 4.60 (95%)
Games | N: 5558 W: 1402 L: 1220 D: 2936
Penta | [5, 581, 1441, 731, 21]
https://furybench.com/test/2475/
What in the...

Threat history

---

Source/search.c

Elo   | 0.66 +- 1.76 (95%)
Games | N: 38108 W: 8795 L: 8723 D: 20590
Penta | [90, 4443, 9937, 4473, 111]
https://furybench.com/test/3078/

search.c: Refactor also set ss->eval to NO_SCORE in check

---

Source/search.c

Elo   | 0.07 +- 1.26 (95%)
Games | N: 76612 W: 17882 L: 17866 D: 40864
Penta | [202, 9148, 19623, 9098, 235]
https://furybench.com/test/3122/

search.c: Simplify and rewrite how eval is handled in search

---

Source/search.c

Elo   | 5.54 +- 3.06 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=128MB
Games | N: 11784 W: 2797 L: 2609 D: 6378
Penta | [3, 1285, 3136, 1457, 11]
https://furybench.com/test/3135/

search.c: Implement Probcut
